export enum A11yControlActions {
  TOGGLE_PANEL = 'TOGGLE_PANEL',
  SET_CACHED_STATE = 'SET_CACHED_STATE',
  TOGGLE_MODE = 'TOGGLE_MODE',
  SET_ACTIVE_COLOR = 'SET_ACTIVE_COLOR',
  SET_FONT_SIZE = 'SET_FONT_SIZE',
  TOGGLE_IS_SERIF = 'TOGGLE_IS_SERIF',
  SET_LINE_HEIGHT = 'SET_LINE_HEIGHT',
  SET_LETTER_SPACING = 'SET_LETTER_SPACING',
  SET_IMAGE_MODE = 'SET_IMAGE_MODE',
}
